name: Run Fooocus Colab and Push Gradio URL

on:
  workflow_dispatch:  # Trigger manually

jobs:
  run-colab:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Set up Python environment
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Create Python script to open Colab
        run: |
          cat > run_colab.py << 'EOF'
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          from selenium.webdriver.chrome.service import Service
          from selenium.webdriver.common.by import By
          from webdriver_manager.chrome import ChromeDriverManager
          import time

          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")
          options.add_argument("--disable-gpu")

          service = Service(ChromeDriverManager().install())
          driver = webdriver.Chrome(service=service, options=options)

          print("Opening notebook...")
          driver.get("https://colab.research.google.com/github/prkpushp/animated/blob/main/Fooocus_Colab.ipynb")
          time.sleep(15)

          # Handle 'Run anyway' if shown
          try:
              run_anyway = driver.find_element(By.XPATH, "//paper-button[contains(., 'Run anyway')]")
              run_anyway.click()
              print("Clicked 'Run anyway'")
              time.sleep(5)
          except:
              print("No 'Run anyway' button.")

          # Click Runtime > Run all
          try:
              driver.find_element(By.ID, "runtime-menu-button").click()
              time.sleep(2)
              driver.find_element(By.XPATH, "//div[contains(text(),'Run all')]").click()
              print("Clicked 'Run all'")
          except Exception as e:
              print("Error clicking Run all:", e)

          # Wait for notebook to finish
          print("Waiting 6 minutes for notebook to execute...")
          time.sleep(360)

          driver.quit()
          print("Done.")
          EOF

      - name: Run Colab notebook via Selenium
        run: python3 run_colab.py
