name: Generate AI Image with Fooocus

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Image prompt (optional override)'
        required: false

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: (Re)sync prompt.txt if overridden
        if: ${{ github.event.inputs.prompt }}
        run: |
          echo "${{ github.event.inputs.prompt }}" > prompt.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add prompt.txt
          git commit -m "Update prompt via workflow" || echo "No changes"
          git push || echo "Push rejected"

      - name: Run Colab via colab-ssh
        uses: addnab/colab-ssh@v2
        with:
          colab_url: ${{ secrets.COLAB_LINK }}
          auth_token: ${{ secrets.COLAB_SSH_TOKEN }}

      - name: Retrieve generated artifact
        uses: actions/download-artifact@v3
        with:
          name: fooocus_output
