name: Foocus Collab

on:
  workflow_dispatch:

jobs:
  generate-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Colab Notebook
        run: |
          cat > Fooocus_Colab.ipynb << 'EOF'
          {
            "cells": [
              {
                "cell_type": "code",
                "execution_count": null,
                "metadata": {},
                "outputs": [],
                "source": [
                  "!pip install pygit2==1.15.1"
                ]
              },
              {
                "cell_type": "code",
                "execution_count": null,
                "metadata": {},
                "outputs": [],
                "source": [
                  "%cd /content"
                ]
              },
              {
                "cell_type": "code",
                "execution_count": null,
                "metadata": {},
                "outputs": [],
                "source": [
                  "!git clone https://github.com/lllyasviel/Fooocus.git"
                ]
              },
              {
                "cell_type": "code",
                "execution_count": null,
                "metadata": {},
                "outputs": [],
                "source": [
                  "%cd /content/Fooocus"
                ]
              },
              {
                "cell_type": "code",
                "execution_count": null,
                "metadata": {},
                "outputs": [],
                "source": [
                  "!python entry_with_update.py --share --always-high-vram"
                ]
              }
            ],
            "metadata": {
              "colab": {
                "name": "Fooocus_Colab.ipynb",
                "provenance": []
              },
              "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
              },
              "language_info": {
                "name": "python"
              }
            },
            "nbformat": 4,
            "nbformat_minor": 0
          }
          EOF

      - name: Commit Colab Notebook
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Fooocus_Colab.ipynb
          git commit -m "Add Fooocus Google Colab Notebook"
          git push
