name: Run Fooocus Colab and Push Gradio URL

on:
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Set up Python
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run Colab Notebook via Headless Browser
        run: |
          cat > run_colab.py << 'EOF'
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          from selenium.webdriver.chrome.service import Service
          from selenium.webdriver.common.by import By
          from webdriver_manager.chrome import ChromeDriverManager
          import time

          options = Options()
          options.add_argument("--headless=new")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")
          options.add_argument("--window-size=1920,1080")

          service = Service(ChromeDriverManager().install())
          driver = webdriver.Chrome(service=service, options=options)

          print("Opening Colab...")
          driver.get("https://colab.research.google.com/github/prkpushp/animated/blob/main/Fooocus_Colab.ipynb")
          time.sleep(15)

          try:
              driver.find_element(By.ID, "runtime-menu-button").click()
              time.sleep(2)
              driver.find_element(By.XPATH, "//div[contains(text(),'Run all')]").click()
              print("Clicked 'Run all'")
          except Exception as e:
              print("Failed to click Run all:", e)

          print("Waiting ~7 minutes for Colab execution...")
          time.sleep(420)

          driver.quit()
          print("✅ Finished automation.")
          EOF

          python3 run_colab.py
