name: Run Google Colab Notebook Headlessly

on:
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Create Python Script to Open and Run Notebook
        run: |
          cat > run_colab.py << 'EOF'
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          from selenium.webdriver.common.by import By
          from webdriver_manager.chrome import ChromeDriverManager
          import time

          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")

          driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)

          driver.get("https://colab.research.google.com/github/prkpushp/animated/blob/main/Fooocus_Colab.ipynb")
          time.sleep(15)

          # Try to click 'Run anyway' if it appears
          try:
              run_anyway = driver.find_element(By.XPATH, "//paper-button[contains(., 'Run anyway')]")
              run_anyway.click()
              time.sleep(5)
          except:
              print("Run anyway button not found, skipping.")

          # Click on Runtime > Run All
          try:
              driver.find_element(By.ID, "runtime-menu-button").click()
              time.sleep(2)
              driver.find_element(By.XPATH, "//div[contains(text(),'Run all')]").click()
              print("Clicked Run All")
          except Exception as e:
              print("Error clicking Run all:", e)

          time.sleep(300)  # Let the notebook run for 5 minutes
          driver.quit()
          EOF

      - name: Run Colab via Selenium
        run: python3 run_colab.py
