name: Run Google Colab Notebook

on:
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          python3 -m pip install selenium webdriver-manager

      - name: Run Colab Notebook via Selenium
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: |
          cat > run_colab.py << EOF
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          from selenium.webdriver.common.by import By
          import time

          options = Options()
          options.add_argument("--headless")
          options.add_argument("--no-sandbox")
          options.add_argument("--disable-dev-shm-usage")

          driver = webdriver.Chrome(options=options)
          driver.get("https://colab.research.google.com/github/prkpushp/animated/blob/main/Fooocus_Colab.ipynb")

          time.sleep(10)

          # Click "Run Anyway" if needed
          try:
              run_anyway = driver.find_element(By.XPATH, "//paper-button[contains(., 'Run anyway')]")
              run_anyway.click()
              time.sleep(5)
          except:
              pass

          # Click Runtime > Run all
          try:
              driver.find_element(By.ID, "runtime-menu-button").click()
              time.sleep(1)
              driver.find_element(By.XPATH, "//div[contains(text(),'Run all')]").click()
              print("Clicked Run All")
          except Exception as e:
              print("Error clicking Run all:", e)

          time.sleep(300)  # wait for 5 minutes for notebook to finish
          driver.quit()
          EOF

          python3 run_colab.py
