name: Generate Animated Video

on:
  schedule:
    - cron: '30 8 * * *' # 2 PM IST (8:30 AM UTC)
    - cron: '30 12 * * *' # 6 PM IST (12:30 PM UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-video:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
          create_credentials_file: true

      # Debug: Check service account key file
      - name: Debug service account key
        run: |
          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "Service account key file found at $GOOGLE_APPLICATION_CREDENTIALS"
            cat $GOOGLE_APPLICATION_CREDENTIALS | jq .client_email
          else
            echo "Error: Service account key file not found"
            exit 1
          fi

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: omega-episode-454707-j5

      # Verify authentication
      - name: Verify Google Cloud authentication
        run: |
          gcloud auth list
          gcloud config set project omega-episode-454707-j5
          if ! gcloud auth print-access-token; then
            echo "Error: Authentication failed"
            exit 1
          fi
          echo "Authentication successful"

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq
          gcloud components install gsutil --quiet

      # Run script
      - name: Run video generation script
        run: |
          chmod +x generate_veo2_video_locally_with_animated_animals_and_music.sh
          ./generate_veo2_video_locally_with_animated_animals_and_music.sh

      # Upload video as artifact
      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        with:
          name: animated-video
          path: ./videos/*.mp4
          retention-days: 7
