name: Generate Music with MusicGen (AudioCraft)

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Describe the music you want (e.g., chill lofi with rain)'
        required: true
        default: 'chill lofi with rain'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1

      - name: Install Python packages (torch, numpy, audiocraft)
        run: |
          pip install torch==2.1.0
          pip install numpy<2.0
          pip install audiocraft

      - name: Generate music from prompt
        run: |
          mkdir -p output
          python - <<EOF
          import os
          import torch
          import scipy.io.wavfile as wavfile
          from audiocraft.models import MusicGen
          from huggingface_hub import login
          
          prompt = os.getenv("INPUT_PROMPT")
          hf_token = os.getenv("HF_TOKEN")
          
          print("🎵 Generating music for prompt:", prompt)
          
          # Authenticate with Hugging Face
          login(token=hf_token)
          
          # Load model and generate music
          device = "cuda" if torch.cuda.is_available() else "cpu"
          model = MusicGen.get_pretrained("facebook/musicgen-medium").to(device)
          model.set_generation_params(duration=30)
          
          waveform = model.generate([prompt], device=device)[0]
          waveform = (waveform * 32767).astype("int16")  # Convert float32 to PCM16
          wavfile.write("output/music.wav", model.sample_rate, waveform)
          print("✅ Saved: output/music.wav")
          EOF
        env:
          INPUT_PROMPT: ${{ github.event.inputs.prompt }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Upload generated music
        uses: actions/upload-artifact@v4
        with:
          name: musicgen-output
          path: output/music.wav
