name: Generate Music with MusicGen (AudioCraft)

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Describe the music you want (e.g., chill lofi with rain)'
        required: true
        default: 'chill lofi with rain'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          ls -l /home/runner/work/_temp/*.sh
          cat /home/runner/work/_temp/*.sh        
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1

      - name: Install Python packages
        run: |
          ls -l /home/runner/work/_temp/*.sh
          cat /home/runner/work/_temp/*.sh
          pip install torch==2.1.0
          ls -l /home/runner/work/_temp/*.sh
          cat /home/runner/work/_temp/*.sh
          pip install "numpy<2.0"
          ls -l /home/runner/work/_temp/*.sh
          cat /home/runner/work/_temp/*.sh
          pip install audiocraft

      - name: Generate music from prompt
        run: |
          mkdir -p output
          python music.py
        env:
          INPUT_PROMPT: ${{ github.event.inputs.prompt }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Upload generated music
        uses: actions/upload-artifact@v4
        with:
          name: musicgen-output
          path: output/music.wav
