name: Generate Music with MusicGen (AudioCraft)

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Describe the music you want (e.g., chill lofi with rain)'
        required: true
        default: 'chill lofi with rain'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          ls -l /home/runner/work/_temp/*.sh
          cat /home/runner/work/_temp/*.sh        
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1

      - name: Install Python packages
        run: |
          pip install torch==2.1.0
          pip install audiocraft
          pip install "numpy<2.0" --force-reinstall
          pip install soundfile

      - name: Debug token visibility
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "::error title=Missing Token::HF_TOKEN is not set!"
            exit 1
          else
            echo "::notice title=Token OK::HF_TOKEN length = ${#HF_TOKEN}"
          fi
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          
      - name: Generate music from prompt
        env:
          INPUT_PROMPT: ${{ github.event.inputs.prompt }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}      
        run: |
          mkdir -p output
          python music.py


      - name: Upload generated music
        uses: actions/upload-artifact@v4
        with:
          name: musicgen-output
          path: output/music.wav
