name: Generate Music via Riffusion

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg libsndfile1
          python -m pip install --upgrade pip
          pip install riffusion

      - name: Generate spectrogram
        env:
          PROMPT: "jazz piano improvisation"
        run: |
          mkdir -p output
          python - <<EOF
          from riffusion import cli
          import os
          prompt = os.getenv("PROMPT")
          img_path = "output/spec.png"
          cli.cli(["image", "--prompt", prompt, "--out", img_path])
          audio_path = "output/clip.wav"
          cli.cli(["image-to-audio", "--image", img_path, "--audio", audio_path])
          EOF

      - name: Upload audio artifact
        uses: actions/upload-artifact@v4
        with:
          name: riffusion-audio
          path: output/*.wav
