name: Generate Music via Riffusion

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Music prompt'
        required: true
        default: 'jazz piano improvisation'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg libsndfile1
          pip install --upgrade pip
          pip install riffusion

      - name: Generate music
        run: |
          mkdir -p output
          PROMPT="${{ github.event.inputs.prompt }}"
          echo "Generating for prompt: $PROMPT"
      
          python3 - <<EOF
      import subprocess
      import os
      
      prompt = os.getenv("PROMPT", "lofi beats with ocean waves")
      img_path = "output/spec.png"
      audio_path = "output/music.wav"
      
      # Generate spectrogram from prompt
      subprocess.run(["riffusion", "image", "--prompt", prompt, "--out", img_path], check=True)
      
      # Convert to audio
      subprocess.run(["riffusion", "image-to-audio", "--image", img_path, "--audio", audio_path], check=True)
      print(f"Generated: {audio_path}")
      EOF


      - name: Upload audio artifact
        uses: actions/upload-artifact@v4
        with:
          name: riffusion-audio
          path: output/music.wav
